language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t congweibai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true congweibai/docker-react npm run test
