language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t congweibai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true congweibai/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-227856811858"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
